### PR TITLE
JSON integration (WIP) + Bug fixes

### PR DESCRIPTION
**Pull request by ScriptSlayer0**
Bugs fixed:
- [X] The display of tables created directories and key pairs when they were not supposed to.

JSON integration:
- [X] Able to create a JSON file
- [X] Support null foreign keys

### CODE REVIEW

**Comment by HarbingerOfFire** [comment]
Bump version to 1.3.0.0 and I'll merge this as part of #34

**Comment by ScriptSlayer0** [comment]
Don't bump now, adding_rows.py doesn't work

**Comment by ScriptSlayer0** [comment]
This error is throwing, after creating a DB with option 6:
`Error adding name to table: New data does not match defined datatypes.`

**Comment by HarbingerOfFire** [comment]
Ok, I think it works now. Test on your side?

**Comment by ScriptSlayer0** [comment]
> Ok, I think it works now. Test on your side?

It works, thanks @HarbingerOfFire

**Comment by HarbingerOfFire** [comment]
Ready for the bump then?

**Comment by ScriptSlayer0** [comment]
Ready

**Pull request merged**
